<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Company;
use App\Models\Department;
use App\Models\Location;
use App\Models\AssetName;
use Carbon\Carbon;
use App\Scopes\CompanyScope;
use Faker\Factory as Faker;

class AssetSeederLarge extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');

        $companyIds = Company::pluck('id')->toArray();
        // if (empty($companyIds)) {
        //     $companyIds[] = DB::table('companies')->insertGetId(['name' => 'PT Bagas Dummy', 'code' => 'BBD', 'created_at' => now(), 'updated_at' => now()]);
        // }

        $deptByCompany = Department::withoutGlobalScope(CompanyScope::class)
            ->get()
            ->groupBy('company_id')
            ->map(fn($g) => $g->pluck('id')->toArray());

        $locByCompany = Location::withoutGlobalScope(CompanyScope::class)
            ->get()
            ->groupBy('company_id')
            ->map(fn($g) => $g->pluck('id')->toArray());

        if ($deptByCompany->isEmpty()) {
            $this->command->error("Tabel departments kosong! Harap isi data master departments dulu.");
            return;
        }

        if ($locByCompany->isEmpty()) {
            $this->command->error("Tabel locations kosong! Harap isi data master locations dulu.");
            return;
        }

        $assetNames = AssetName::withoutGlobalScope(CompanyScope::class)->get();

        if ($assetNames->isEmpty()) {
            $this->command->error("Tabel asset_names kosong! Harap isi data master asset names dulu.");
            return;
        }

        $totalRecords = 100; // Target 50.000 Data
        $chunkSize = 50;     // Masukkan per 1.000 baris (Biar RAM hemat & Cepat)

        $this->command->info("Memulai proses seeding {$totalRecords} aset...");
        $bar = $this->command->getOutput()->createProgressBar($totalRecords);
        $bar->start();

        $data = [];

        // 3. GENERATE DATA
        for ($i = 1; $i <= $totalRecords; $i++) {

            $companyId = $faker->randomElement($companyIds);
            $selectedAssetName = $assetNames->random();

            $commUsefulLife = $selectedAssetName->commercial_useful_life ?? 48;
            $fiscalUsefulLife = $selectedAssetName->fiscal_useful_life ?? 48;

            $acqValue = $faker->numberBetween(5000000, 2000000000);
            $acqValue = floor($acqValue / 1000) * 1000;

            $buyDate = Carbon::now()->subDays($faker->numberBetween(1, 1800));
            $startDepreDate = $buyDate->copy()->startOfMonth(); // Depresiasi mulai bulan depannya

            $accumDepre = 0;
            $nbv = $acqValue;

            $data[] = [
                'asset_number' => 'FA-DUMMY-' . str_pad($i, 6, '0', STR_PAD_LEFT), // FA-DUMMY-000001
                'asset_code' => $faker->uuid,
                'asset_name_id' => $selectedAssetName->id,
                'asset_type' => 'FA',
                'status' => 'Active', // Hanya generate yang aktif
                'description' => 'Generated by Seeder ' . $faker->sentence(3),
                'detail' => null,
                'pareto' => null,
                'unit_no' => null,
                'user' => $faker->name,
                'sn' => $faker->uuid,
                'sn_chassis' => null,
                'sn_engine' => null,
                'production_year' => $buyDate->format('Y-m-d'),
                'po_no' => 'PO-' . $faker->bothify('#####??'),
                'location_id' => $faker->randomElement($locByCompany[$companyId] ?? [null]),
                'department_id' => $faker->randomElement($deptByCompany[$companyId] ?? [null]),
                'quantity' => 1,

                'capitalized_date'  => $buyDate->format('Y-m-d'),
                'start_depre_date'  => $startDepreDate->format('Y-m-d'),

                'acquisition_value' => $acqValue,
                'current_cost'      => $acqValue,

                // Commercial
                'commercial_useful_life_month' => $commUsefulLife,
                'commercial_accum_depre'       => $accumDepre, // 0, Biar Job yang kerja
                'commercial_nbv'               => $nbv,        // Masih Full

                // Fiscal (Samakan dulu logicnya)
                'fiscal_useful_life_month' => $fiscalUsefulLife,
                'fiscal_accum_depre' => $accumDepre,
                'fiscal_nbv' => $nbv,

                'remaks' => null,
                'company_id' => $companyId,
                'created_at' => now(),
                'updated_at' => now(),
            ];

            // Masukkan ke DB setiap kelipatan 1000 data (Chunking)
            if (count($data) >= $chunkSize) {
                DB::table('assets')->insert($data);
                $data = []; // Kosongkan array memory
                $bar->advance($chunkSize);
            }
        }

        // Masukkan sisa data jika ada
        if (!empty($data)) {
            DB::table('assets')->insert($data);
            $bar->advance(count($data));
        }

        $bar->finish();
        $this->command->info("\nSeeding Selesai! " . $totalRecords . " Data Aset Siap Disiksa.");
    }
}