<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Company;
use App\Models\Department;
use App\Models\Location;
use App\Models\AssetName;
use Carbon\Carbon;
use App\Scopes\CompanyScope;
use Faker\Factory as Faker;
use Illuminate\Support\Str;

class AssetSeederLarge extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Jalankan dengan:
     *   php artisan db:seed --class=AssetSeederLarge
     *
     * Seeder akan meminta input company dan jumlah aset secara interaktif.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');

        // ── Pilih company secara interaktif ──────────────────────────────
        $companies = Company::all();
        if ($companies->isEmpty()) {
            $this->command->error("Tabel companies kosong!");
            return;
        }

        $choices = $companies->mapWithKeys(fn($c) => [$c->id => "[{$c->id}] {$c->name}"])->toArray();
        $choices[0] = '[0] Semua Company';
        ksort($choices);

        $chosen = $this->command->choice('Pilih company yang akan di-seed:', $choices, 0);
        $chosenId = (int) explode(']', explode('[', $chosen)[1])[0];

        if ($chosenId === 0) {
            $companyIds = $companies->pluck('id')->toArray();
            $companyLabel = 'ALL';
            $this->command->info("Seeding untuk semua company.");
        } else {
            $company = $companies->firstWhere('id', $chosenId);
            $companyIds = [$company->id];
            $companyLabel = strtoupper(substr($company->name, 0, 3));
            $this->command->info("Seeding untuk company: {$company->name}");
        }

        // ── Jumlah aset ───────────────────────────────────────────────────
        $totalRecords = (int) $this->command->ask('Berapa aset yang ingin di-seed?', 100);
        $chunkSize = 50;

        // ── Data master ───────────────────────────────────────────────────
        $deptByCompany = Department::withoutGlobalScope(CompanyScope::class)
            ->get()
            ->groupBy('company_id')
            ->map(fn($g) => $g->pluck('id')->toArray());

        $locByCompany = Location::withoutGlobalScope(CompanyScope::class)
            ->get()
            ->groupBy('company_id')
            ->map(fn($g) => $g->pluck('id')->toArray());

        if ($deptByCompany->isEmpty()) {
            $this->command->error("Tabel departments kosong! Harap isi data master departments dulu.");
            return;
        }

        if ($locByCompany->isEmpty()) {
            $this->command->error("Tabel locations kosong! Harap isi data master locations dulu.");
            return;
        }

        $assetNames = AssetName::withoutGlobalScope(CompanyScope::class)->get();

        if ($assetNames->isEmpty()) {
            $this->command->error("Tabel asset_names kosong! Harap isi data master asset names dulu.");
            return;
        }

        // Prefix: FA-[3 huruf company]
        $prefix = 'FA-' . $companyLabel;

        $this->command->info("Memulai proses seeding {$totalRecords} aset dengan prefix [{$prefix}]...");
        $bar = $this->command->getOutput()->createProgressBar($totalRecords);
        $bar->start();

        $data = [];

        // ── Generate data ─────────────────────────────────────────────────
        for ($i = 1; $i <= $totalRecords; $i++) {

            $companyId = $faker->randomElement($companyIds);
            $selectedAssetName = $assetNames->random();

            $commUsefulLife  = ($selectedAssetName->commercial ?? 4) * 12;
            $fiscalUsefulLife = ($selectedAssetName->fiscal ?? 4) * 12;

            $acqValue = floor($faker->numberBetween(5_000_000, 2_000_000_000) / 1000) * 1000;
            $buyDate = Carbon::now()->subDays($faker->numberBetween(1, 1800));
            $startDepreDate = $buyDate->copy()->startOfMonth(); // Depresiasi mulai bulan depannya

            $data[] = [
                'asset_number' => $prefix . '-' . str_pad($i, 5, '0', STR_PAD_LEFT),
                'asset_code' => strtolower(substr(Str::uuid()->toString(), 0, 10)),
                'asset_name_id' => $selectedAssetName->id,
                'asset_type' => 'FA',
                'status' => 'Active',
                'description' => 'Generated by Seeder ' . $faker->sentence(3),
                'detail' => null,
                'pareto' => null,
                'unit_no' => null,
                'user' => $faker->name,
                'sn' => $faker->uuid,
                'sn_chassis' => null,
                'sn_engine' => null,
                'production_year' => $buyDate->format('Y-m-d'),
                'po_no' => 'PO-' . $faker->bothify('#####??'),
                'location_id' => $faker->randomElement($locByCompany[$companyId] ?? [null]),
                'department_id' => $faker->randomElement($deptByCompany[$companyId] ?? [null]),
                'quantity' => 1,

                'capitalized_date' => $buyDate->format('Y-m-d'),
                'start_depre_date' => $startDepreDate->format('Y-m-d'),

                'acquisition_value' => $acqValue,
                'current_cost'      => $acqValue,

                'commercial_useful_life_month' => $commUsefulLife,
                'commercial_accum_depre' => 0,
                'commercial_nbv' => $acqValue,

                'fiscal_useful_life_month' => $fiscalUsefulLife,
                'fiscal_accum_depre' => 0,
                'fiscal_nbv' => $acqValue,

                'remaks' => null,
                'company_id' => $companyId,
                'created_at' => now(),
                'updated_at' => now(),
            ];

            if (count($data) >= $chunkSize) {
                DB::table('assets')->insert($data);
                $data = [];
                $bar->advance($chunkSize);
            }
        }

        if (!empty($data)) {
            DB::table('assets')->insert($data);
            $bar->advance(count($data));
        }

        $bar->finish();
        $this->command->newLine();
        $this->command->info("Seeding Selesai! {$totalRecords} Data Aset berhasil dibuat.");
    }
}